export const MY_INFORMATION_ROUTER_ROOT = '/my';
export const MY_INFORMATION_PROFILE_PATH = MY_INFORMATION_ROUTER_ROOT;
export const MY_INFORMATION_CREATE_DESIGN_PATH = `${MY_INFORMATION_ROUTER_ROOT}/designs/create`;
