export const REPEAT_DETAIL_APPROXIMATION = {
  STITCH_REPEAT_CALCULATE_ROUND_DOWN: 'STITCH_REPEAT_CALCULATE_ROUND_DOWN',
  STITCH_REPEAT_CALCULATE_ROUND: 'STITCH_REPEAT_CALCULATE_ROUND',
  STITCH_REPEAT_CALCULATE_ROUND_UP: 'STITCH_REPEAT_CALCULATE_ROUND_UP',
  ROW_REPEAT_CALCULATE_ROUND_DOWN: 'ROW_REPEAT_CALCULATE_ROUND_DOWN',
  ROW_REPEAT_CALCULATE_ROUND: 'ROW_REPEAT_CALCULATE_ROUND',
  ROW_REPEAT_CALCULATE_ROUND_UP: 'ROW_REPEAT_CALCULATE_ROUND_UP',
} as const;

export type REPEAT_DETAIL_APPROXIMATION_TYPE = typeof REPEAT_DETAIL_APPROXIMATION[keyof typeof REPEAT_DETAIL_APPROXIMATION];

export const REPEAT_APPROXIMATION = {
  STITCH_REPEAT: 'STITCH_REPEAT',
  ROW_REPEAT: 'ROW_REPEAT',
  NOT_CALCULATE: 'NOT_CALCULATE',
} as const;

export const REPEAT_DISPLAY_APPROXIMATION = {
  STITCH_REPEAT: '코 반복',
  ROW_REPEAT: '단 반복',
  NOT_CALCULATE: '계산 안 함',
} as const;

export const STITCH_REPEAT_DISPLAY_DETAIL_APPROXIMATION = {
  [REPEAT_DETAIL_APPROXIMATION.STITCH_REPEAT_CALCULATE_ROUND_DOWN]: '코 내림',
  [REPEAT_DETAIL_APPROXIMATION.STITCH_REPEAT_CALCULATE_ROUND]: '코 반올림',
  [REPEAT_DETAIL_APPROXIMATION.STITCH_REPEAT_CALCULATE_ROUND_UP]: '코 올림',
} as const;

export const ROW_REPEAT_DISPLAY_DETAIL_APPROXIMATION = {
  [REPEAT_DETAIL_APPROXIMATION.ROW_REPEAT_CALCULATE_ROUND_DOWN]: '단 내림',
  [REPEAT_DETAIL_APPROXIMATION.ROW_REPEAT_CALCULATE_ROUND]: '단 반올림',
  [REPEAT_DETAIL_APPROXIMATION.ROW_REPEAT_CALCULATE_ROUND_UP]: '단 올림',
} as const;
