name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist

      - name: Deploy to Firebase
        uses: joinflux/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: '${{ job.status }}' ===  'success' ? `*[${process.env.AS_REPO}]*\n${process.env.AS_MESSAGE}(${process.env.AS_COMMIT})이 배포되었습니다 :rocket:` : `*[${process.env.AS_REPO}]*\n${process.env.AS_MESSAGE}(${process.env.AS_COMMIT}) 배포가 실패했습니다. :sob:`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
